# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bopmite/hyperlog

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bopmite/hyperlog

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bopmite/hyperlog/CMakeFiles /home/bopmite/hyperlog//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bopmite/hyperlog/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hyperlog

# Build rule for target.
hyperlog: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hyperlog
.PHONY : hyperlog

# fast build rule for target.
hyperlog/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyperlog.dir/build.make CMakeFiles/hyperlog.dir/build
.PHONY : hyperlog/fast

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

src/engine/cache/rid_cache.o: src/engine/cache/rid_cache.cpp.o
.PHONY : src/engine/cache/rid_cache.o

# target to build an object file
src/engine/cache/rid_cache.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyperlog.dir/build.make CMakeFiles/hyperlog.dir/src/engine/cache/rid_cache.cpp.o
.PHONY : src/engine/cache/rid_cache.cpp.o

src/engine/cache/rid_cache.i: src/engine/cache/rid_cache.cpp.i
.PHONY : src/engine/cache/rid_cache.i

# target to preprocess a source file
src/engine/cache/rid_cache.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyperlog.dir/build.make CMakeFiles/hyperlog.dir/src/engine/cache/rid_cache.cpp.i
.PHONY : src/engine/cache/rid_cache.cpp.i

src/engine/cache/rid_cache.s: src/engine/cache/rid_cache.cpp.s
.PHONY : src/engine/cache/rid_cache.s

# target to generate assembly for a file
src/engine/cache/rid_cache.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyperlog.dir/build.make CMakeFiles/hyperlog.dir/src/engine/cache/rid_cache.cpp.s
.PHONY : src/engine/cache/rid_cache.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyperlog.dir/build.make CMakeFiles/hyperlog.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyperlog.dir/build.make CMakeFiles/hyperlog.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyperlog.dir/build.make CMakeFiles/hyperlog.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/net/routes/append.o: src/net/routes/append.cpp.o
.PHONY : src/net/routes/append.o

# target to build an object file
src/net/routes/append.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyperlog.dir/build.make CMakeFiles/hyperlog.dir/src/net/routes/append.cpp.o
.PHONY : src/net/routes/append.cpp.o

src/net/routes/append.i: src/net/routes/append.cpp.i
.PHONY : src/net/routes/append.i

# target to preprocess a source file
src/net/routes/append.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyperlog.dir/build.make CMakeFiles/hyperlog.dir/src/net/routes/append.cpp.i
.PHONY : src/net/routes/append.cpp.i

src/net/routes/append.s: src/net/routes/append.cpp.s
.PHONY : src/net/routes/append.s

# target to generate assembly for a file
src/net/routes/append.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyperlog.dir/build.make CMakeFiles/hyperlog.dir/src/net/routes/append.cpp.s
.PHONY : src/net/routes/append.cpp.s

src/util/crc32c.o: src/util/crc32c.cpp.o
.PHONY : src/util/crc32c.o

# target to build an object file
src/util/crc32c.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyperlog.dir/build.make CMakeFiles/hyperlog.dir/src/util/crc32c.cpp.o
.PHONY : src/util/crc32c.cpp.o

src/util/crc32c.i: src/util/crc32c.cpp.i
.PHONY : src/util/crc32c.i

# target to preprocess a source file
src/util/crc32c.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyperlog.dir/build.make CMakeFiles/hyperlog.dir/src/util/crc32c.cpp.i
.PHONY : src/util/crc32c.cpp.i

src/util/crc32c.s: src/util/crc32c.cpp.s
.PHONY : src/util/crc32c.s

# target to generate assembly for a file
src/util/crc32c.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyperlog.dir/build.make CMakeFiles/hyperlog.dir/src/util/crc32c.cpp.s
.PHONY : src/util/crc32c.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... run"
	@echo "... hyperlog"
	@echo "... src/engine/cache/rid_cache.o"
	@echo "... src/engine/cache/rid_cache.i"
	@echo "... src/engine/cache/rid_cache.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/net/routes/append.o"
	@echo "... src/net/routes/append.i"
	@echo "... src/net/routes/append.s"
	@echo "... src/util/crc32c.o"
	@echo "... src/util/crc32c.i"
	@echo "... src/util/crc32c.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

